[package]
name = "rota-korpuss-gen"
version = "0.1.0"
authors = ["Blake"]

[dependencies]
csv = "1.0.0-beta.5"
error-chain = "0.11.0"
itertools = "0.7.3"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
structopt = "0.1.0"
structopt-derive = "0.1.0"
