---
people:
  nurses:
    - name: Liga
    - name: Alise
    - name: Aļona
    - name: Katrina
    - name: Lenins
    - name: Angela
      days:
        - monday
        - tuesday
        - thursday
        - friday
    - name: James
    - name: Koshka
    - name: Zaklina
    - name: Karlis
    - name: "Zane G."
      rooms:
        - "electrophysiology room"
    - name: Kacha
      trainee: true
    - name: Sara
      trainee: true
    - name: Sakura
      trainee: true
    - name: Milestiba
    - name: Agnese
    - name: Lote
    - name: Toms

  supporters:
    - name: Sandra
    - name: Ieva
    - name: Ilze
      days:
        - monday
        - tuesday
        - thursday
        - friday
    - name: Trumps
    - name: Daiga
    - name: Kiwis
    - name: Sigita
    - name: "Dace P."

nurses-jobs:
  - cathlab
  - xray

rooms:
  - "rm.1"
  - "rm.2"
  - "rm.3"
  - "rm.4"
  - "rm.6"
  - "electrophysiology room"

job-room-sep: ""

dates:
  month: february
  start-day: thursday
  start: 1
  end: 28
  year: 2018

excel: true
