[config]
skip_core_tasks = true

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.zip]
script = [
'''
zip rota-gen.zip -j config* target/release/rota-korpuss-gen.exe
echo "Archive generated in rota-gen.zip"
'''
]

[tasks.default]
dependencies = ["build", "zip"]
