[config]
skip_core_tasks = true

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.zip]
script = [
'''
zip rota-gen-${CARGO_MAKE_CRATE_VERSION}.zip -j config* target/release/rota-korpuss-gen.exe
echo "Archive generated in rota-gen-${CARGO_MAKE_CRATE_VERSION}.zip"
'''
]

[tasks.default]
dependencies = ["build", "zip"]
