[config]
skip_core_tasks = true

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.zip]
script_runner = "@shell"
script = [
'''
zip rota-gen-${CARGO_MAKE_CRATE_VERSION}.zip -j config* target/release/rota-korpuss-gen.exe
echo "Archive generated in rota-gen-${CARGO_MAKE_CRATE_VERSION}.zip"
'''
]

[tasks.default]
dependencies = ["build", "zip"]

[tasks.off_stats]
script_runner = "@shell"
script = [
'''
cat rota.csv | tail -n +3 | ruby offs.rb | sort -n | tail -n +2 | xsv stats | xsv select 3- | xsv table
# cat rota.csv | tail -n +2 | xsv frequency | grep -v ",1\$" | grep -v ",off" | xsv select 2- | xsv table
'''
]

[tasks.run]
script_runner = "@shell"
script = [
'''
cargo run -- --no-block
'''
]

[tasks.stats]
dependencies = ["build", "run", "off_stats"]
